import = [
    "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 10
